import type { Metadata } from "next";
import { caveat, greatVibes, georgia } from "@/fonts/_fonts";
import "@/styles/globals.css";
import Header from "@/header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${georgia.variable} ${caveat.variable} ${greatVibes.variable} font-sans antialiased`}
      >
        <Header />
        <main className="mx-auto max-w-7xl px-4">{children}</main>
      </body>
    </html>
  );
}
