import { IContentArticle } from "@/type/content";

import one from "@/images/news/09.2025/news_19.09.25/129113.jpeg";
import { news_19_Slider } from "./news_19_Slider";

export const news_19: IContentArticle = {
  id: "international-rehabilitation-forum",
  isoDate: "2025-09-19T00:00:00.000Z",
  layoutType: "sliderLeft",
  urlImg: one,
  slides: news_19_Slider,
  translations: {
    ua: {
      title: "Мер Одеси відкрив роботу Міжнародного форуму з реабілітації.",
      displayDate: "19 вересня 2025 р.",
      alt: "Фото",
      p_01: `18 вересня 2025 року Одеський міський голова Геннадій Труханов відкрив роботу міжнародної платформи «Bionic Forum: Ukraine’s Rehabilitation & Reforms». У роботі форуму взяли участь: представники Верховної Ради України, Міністерства охорони здоров'я України, Міністерства у справах ветеранів України, закладів охорони здоров'я, соціального захисту, вищої медичної освіти, реабілітаційних центрів, виробники засобів реабілітації та протезування, представники громадських організацій та ветеранських об'єднань.`,
      p_02: `Захід об'єднав провідних фахівців з одинадцяти регіонів України та з інших країн. Учасники форуму протягом двох днів обговорять питання державної політики та міжнародного досвіду в галузі реабілітації військових та цивільних, новітні технології у реабілітації, зокрема екзоскелети, роботизовані протези, біонічні імпланти, біотехнології у створенні інноваційних протезів та ортезів, актуальні аспекти психологічної реабілітації та соціальної адаптації тощо. `,
      p_03: `“Цей форум — стартовий майданчик для реальних дій. Бо питання протезування є не лише медичним — це інтеграція людей з інвалідністю в активне соціальне життя, а отже, в економічне майбутнє України. Сьогодні Одеса має всі передумови, щоб стати центром реабілітаційного відновлення країни. Розгалужена медична мережа, реабілітаційна, рекреаційна, освітня та спортивна база, налагоджена взаємодія з неурядовим сектором та бізнесом, а також міжнародні звʼязки створюють унікальне середовище для системної реабілітації”, — зазначив мер Одеси Геннадій Труханов.`,
      p_04: `Міською владою Одеси ведеться системна робота з розбудови системи реабілітації ветеранів. Сучасні реабілітаційні відділення працюють у чотирьох міських лікарнях. Також до надання амбулаторної реабілітації залучені Центри первинної медико-санітарної допомоги та консультативно-діагностичні центри. В амбулаторних закладах надається психологічна реабілітація, а в міській клінічній лікарні №10 працює Центр ментального здоров'я.`,
      p_05: `Наразі на базі однієї з міських лікарень у рекреаційній зоні Одеси розпочато створення потужного Південноукраїнського реабілітаційного центру. Це буде комплексний простір, де поєднаються медична допомога, освітні програми, адаптивний спорт та соціальна інтеграція. Крім того, проводиться ремонт і розширення відділення реабілітації в міській клінічній лікарні №1.`,
      p_06: `До реабілітацій ветеранів активно долучаються методики адаптивного спорту. Нещодавно одеська команда повернулася з Венеціанської регати, де пройшла Гранд-каналом під українським і одеським прапорами. `,
      p_07: `Міжнародна платформа «Bionic Forum: Ukraine’s Rehabilitation & Reforms» в Одесі стане стратегічним майданчиком для розвитку національної системи реабілітації, забезпечить конструктивний діалог між муніципальним, національним та міжнародним рівнями для впровадження ефективних політик та рішень. Ця подія спрямована на впровадження інноваційних технологій та залучення міжнародного досвіду для формування довгострокової стратегії розвитку реабілітаційної системи.`,
    },
    ru: {
      title: `Мэр Одессы открыл работу Международного форума по реабилитации.`,
      displayDate: `19 сентября 2025 г.`,
      alt: "Фото",
      p_01: `18 сентября 2025 года Одесский городской голова Геннадий Труханов открыл работу международной платформы «Bionic Forum: Ukraine’s Rehabilitation & Reforms». В работе форума приняли участие: представители Верховной Рады Украины, Министерства здравоохранения Украины, Министерства по делам ветеранов Украины, учреждений здравоохранения, социальной защиты, высшего медицинского образования, реабилитационных центров, производители средств реабилитации и протезирования, представители общественных организаций и ветеранских объединений.`,
      p_02: `Мероприятие объединило ведущих специалистов из одиннадцати регионов Украины и других стран. Участники форума в течение двух дней обсудят вопросы государственной политики и международного опыта в области реабилитации военных и гражданских, новейшие технологии в реабилитации, в частности экзоскелеты, роботизированные протезы, бионические импланты, биотехнологии в создании инновационных протезов и ортезов, актуальные аспекты психологической реабилитации и социальной адаптации и т.д.`,
      p_03: `«Этот форум — стартовая площадка для реальных действий. Потому что вопрос протезирования не только медицинский — это интеграция людей с инвалидностью в активную социальную жизнь, а значит, в экономическое будущее Украины. Сегодня у Одессы есть все предпосылки, чтобы стать центром реабилитационного восстановления страны. Разветвленная медицинская сеть, реабилитационная, рекреационная, образовательная и спортивная база, налаженное взаимодействие с неправительственным сектором и бизнесом, а также международные связи создают уникальную среду для системной реабилитации», — отметил мэр Одессы Геннадий Труханов.`,
      p_04: `Городскими властями Одессы ведется системная работа по развитию системы реабилитации ветеранов. Современные реабилитационные отделения работают в четырех городских больницах. Также к оказанию амбулаторной реабилитации привлечены Центры первичной медико-санитарной помощи и консультативно-диагностические центры. В амбулаторных учреждениях предоставляется психологическая реабилитация, а в городской клинической больнице №10 работает Центр ментального здоровья.`,
      p_05: `В настоящее время на базе одной из городских больниц в рекреационной зоне Одессы начато создание мощного Южноукраинского реабилитационного центра. Это будет комплексное пространство, где объединятся медицинская помощь, образовательные программы, адаптивный спорт и социальная интеграция. Кроме того, проводится ремонт и расширение отделения реабилитации в городской клинической больнице №1.`,
      p_06: `К реабилитации ветеранов активно привлекаются методики адаптивного спорта. Недавно одесская команда вернулась с Венецианской регаты, где прошла по Гранд-каналу под украинским и одесским флагами.`,
      p_07: `Международная платформа «Bionic Forum: Ukraine’s Rehabilitation & Reforms» в Одессе станет стратегической площадкой для развития национальной системы реабилитации, обеспечит конструктивный диалог между муниципальным, национальным и международным уровнями для внедрения эффективных политик и решений. Это событие направлено на внедрение инновационных технологий и привлечение международного опыта для формирования долгосрочной стратегии развития реабилитационной системы.`,
    },
    en: {
      title: `The Mayor of Odesa opened the International Rehabilitation Forum.`,
      displayDate: `September 19, 2025`,
      alt: "Фото",
      p_01: `On September 18, 2025, Odesa Mayor Gennadiy Trukhanov opened the international platform "Bionic Forum: Ukraine’s Rehabilitation & Reforms". The forum was attended by representatives of the Verkhovna Rada of Ukraine, the Ministry of Health of Ukraine, the Ministry for Veterans Affairs of Ukraine, healthcare and social protection institutions, higher medical education institutions, rehabilitation centers, manufacturers of rehabilitation and prosthetics equipment, representatives of public organizations, and veteran associations.`,
      p_02: `The event brought together leading specialists from eleven regions of Ukraine and other countries. Over two days, the forum participants will discuss issues of state policy and international experience in the rehabilitation of military and civilians, the latest technologies in rehabilitation, including exoskeletons, robotic prostheses, bionic implants, biotechnologies in the creation of innovative prostheses and orthoses, current aspects of psychological rehabilitation and social adaptation, etc.`,
      p_03: `"This forum is a starting point for real action. Because the issue of prosthetics is not only a medical one — it is the integration of people with disabilities into active social life, and therefore, into the economic future of Ukraine. Today, Odesa has all the prerequisites to become the center of the country's rehabilitation recovery. An extensive medical network, rehabilitation, recreational, educational, and sports facilities, established cooperation with the non-governmental sector and business, as well as international connections, create a unique environment for systemic rehabilitation," said Odesa Mayor Gennadiy Trukhanov.`,
      p_04: `The Odesa city authorities are systematically working on developing a rehabilitation system for veterans. Modern rehabilitation departments operate in four city hospitals. Primary health care centers and consultative and diagnostic centers are also involved in providing outpatient rehabilitation. Psychological rehabilitation is provided in outpatient facilities, and a Mental Health Center operates in City Clinical Hospital No. 10.`,
      p_05: `Currently, the creation of a powerful Southern Ukrainian Rehabilitation Center has begun on the basis of one of the city hospitals in the recreational area of Odesa. It will be a comprehensive space combining medical care, educational programs, adaptive sports, and social integration. In addition, the rehabilitation department at City Clinical Hospital No. 1 is being renovated and expanded.`,
      p_06: `Adaptive sports methods are actively involved in the rehabilitation of veterans. Recently, the Odesa team returned from the Venetian Regatta, where they sailed along the Grand Canal under the Ukrainian and Odesa flags.`,
      p_07: `The international platform "Bionic Forum: Ukraine’s Rehabilitation & Reforms" in Odesa will become a strategic platform for the development of the national rehabilitation system, ensuring a constructive dialogue between the municipal, national, and international levels for the implementation of effective policies and solutions. This event is aimed at introducing innovative technologies and attracting international experience to form a long-term strategy for the development of the rehabilitation system.`,
    },
  },
};
