import { countryFlag } from "./countryFlag";

export const countryInfo = {
  ua: {
    AD: { code: "AD", name: "Андорра", currency: "EUR", flag: countryFlag.AD },
    AE: {
      code: "AE",
      name: "Об'єднані Арабські Емірати",
      currency: "AED",
      flag: countryFlag.AE,
    },
    AF: {
      code: "AF",
      name: "Афганістан",
      currency: "AFN",
      flag: countryFlag.AF,
    },
    AG: {
      code: "AG",
      name: "Антигуа і Барбуда",
      currency: "XCD",
      flag: countryFlag.AG,
    },
    AI: { code: "AI", name: "Ангілья", currency: "XCD", flag: countryFlag.AI },
    AL: { code: "AL", name: "Албанія", currency: "ALL", flag: countryFlag.AL },
    AM: { code: "AM", name: "Вірменія", currency: "AMD", flag: countryFlag.AM },
    AO: { code: "AO", name: "Ангола", currency: "AOA", flag: countryFlag.AO },
    AQ: { code: "AQ", name: "Антарктида", currency: "", flag: countryFlag.AQ },
    AR: {
      code: "AR",
      name: "Аргентина",
      currency: "ARS",
      flag: countryFlag.AR,
    },
    AS: {
      code: "AS",
      name: "Американське Самоа",
      currency: "USD",
      flag: countryFlag.AS,
    },
    AT: { code: "AT", name: "Австрія", currency: "EUR", flag: countryFlag.AT },
    AU: {
      code: "AU",
      name: "Австралія",
      currency: "AUD",
      flag: countryFlag.AU,
    },
    AW: { code: "AW", name: "Аруба", currency: "AWG", flag: countryFlag.AW },
    AX: {
      code: "AX",
      name: "Аландські острови",
      currency: "EUR",
      flag: countryFlag.AX,
    },
    AZ: {
      code: "AZ",
      name: "Азербайджан",
      currency: "AZN",
      flag: countryFlag.AZ,
    },
    BA: {
      code: "BA",
      name: "Боснія і Герцеговина",
      currency: "BAM",
      flag: countryFlag.BA,
    },
    BB: { code: "BB", name: "Барбадос", currency: "BBD", flag: countryFlag.BB },
    BD: {
      code: "BD",
      name: "Бангладеш",
      currency: "BDT",
      flag: countryFlag.BD,
    },
    BE: { code: "BE", name: "Бельгія", currency: "EUR", flag: countryFlag.BE },
    BF: {
      code: "BF",
      name: "Буркіна-Фасо",
      currency: "XOF",
      flag: countryFlag.BF,
    },
    BG: { code: "BG", name: "Болгарія", currency: "BGN", flag: countryFlag.BG },
    BH: { code: "BH", name: "Бахрейн", currency: "BHD", flag: countryFlag.BH },
    BI: { code: "BI", name: "Бурунді", currency: "BIF", flag: countryFlag.BI },
    BJ: { code: "BJ", name: "Бенін", currency: "XOF", flag: countryFlag.BJ },
    BL: {
      code: "BL",
      name: "Сен-Бартелемі",
      currency: "EUR",
      flag: countryFlag.BL,
    },
    BM: {
      code: "BM",
      name: "Бермудські Острови",
      currency: "BMD",
      flag: countryFlag.BM,
    },
    BN: {
      code: "BN",
      name: "Бруней-Даруссалам",
      currency: "BND",
      flag: countryFlag.BN,
    },
    BO: {
      code: "BO",
      name: "Болівія (Багатонаціональна Держава)",
      currency: "BOB",
      flag: countryFlag.BO,
    },
    BQ: {
      code: "BQ",
      name: "Бонайре, Сінт-Естатіус і Саба",
      currency: "USD",
      flag: countryFlag.BQ,
    },
    BR: { code: "BR", name: "Бразилія", currency: "BRL", flag: countryFlag.BR },
    BS: {
      code: "BS",
      name: "Багамські Острови",
      currency: "BSD",
      flag: countryFlag.BS,
    },
    BT: { code: "BT", name: "Бутан", currency: "BTN", flag: countryFlag.BT },
    BV: {
      code: "BV",
      name: "Острів Буве",
      currency: "NOK",
      flag: countryFlag.BV,
    },
    BW: { code: "BW", name: "Ботсвана", currency: "BWP", flag: countryFlag.BW },
    BY: { code: "BY", name: "Білорусь", currency: "BYN", flag: countryFlag.BY },
    BZ: { code: "BZ", name: "Беліз", currency: "BZD", flag: countryFlag.BZ },
    CA: { code: "CA", name: "Канада", currency: "CAD", flag: countryFlag.CA },
    CC: {
      code: "CC",
      name: "Кокосові (Кілінг) Острови",
      currency: "AUD",
      flag: countryFlag.CC,
    },
    CD: {
      code: "CD",
      name: "Конго, Демократична Республіка",
      currency: "CDF",
      flag: countryFlag.CD,
    },
    CF: {
      code: "CF",
      name: "Центральноафриканська Республіка",
      currency: "XAF",
      flag: countryFlag.CF,
    },
    CG: { code: "CG", name: "Конго", currency: "XAF", flag: countryFlag.CG },
    CH: {
      code: "CH",
      name: "Швейцарія",
      currency: "CHF",
      flag: countryFlag.CH,
    },
    CI: {
      code: "CI",
      name: "Кот-д'Івуар",
      currency: "XOF",
      flag: countryFlag.CI,
    },
    CK: {
      code: "CK",
      name: "Острови Кука",
      currency: "NZD",
      flag: countryFlag.CK,
    },
    CL: { code: "CL", name: "Чилі", currency: "CLP", flag: countryFlag.CL },
    CM: { code: "CM", name: "Камерун", currency: "XAF", flag: countryFlag.CM },
    CN: { code: "CN", name: "Китай", currency: "CNY", flag: countryFlag.CN },
    CO: { code: "CO", name: "Колумбія", currency: "COP", flag: countryFlag.CO },
    CR: {
      code: "CR",
      name: "Коста-Рика",
      currency: "CRC",
      flag: countryFlag.CR,
    },
    CU: { code: "CU", name: "Куба", currency: "CUP", flag: countryFlag.CU },
    CV: {
      code: "CV",
      name: "Кабо-Верде",
      currency: "CVE",
      flag: countryFlag.CV,
    },
    CW: { code: "CW", name: "Кюрасао", currency: "ANG", flag: countryFlag.CW },
    CX: {
      code: "CX",
      name: "Острів Різдва",
      currency: "AUD",
      flag: countryFlag.CX,
    },
    CY: { code: "CY", name: "Кіпр", currency: "EUR", flag: countryFlag.CY },
    CZ: { code: "CZ", name: "Чехія", currency: "CZK", flag: countryFlag.CZ },
    DE: {
      code: "DE",
      name: "Німеччина",
      currency: "EUR",
      flag: countryFlag.DE,
    },
    DJ: { code: "DJ", name: "Джибуті", currency: "DJF", flag: countryFlag.DJ },
    DK: { code: "DK", name: "Данія", currency: "DKK", flag: countryFlag.DK },
    DM: { code: "DM", name: "Домініка", currency: "XCD", flag: countryFlag.DM },
    DO: {
      code: "DO",
      name: "Домініканська Республіка",
      currency: "DOP",
      flag: countryFlag.DO,
    },
    DZ: { code: "DZ", name: "Алжир", currency: "DZD", flag: countryFlag.DZ },
    EC: { code: "EC", name: "Еквадор", currency: "USD", flag: countryFlag.EC },
    EE: { code: "EE", name: "Естонія", currency: "EUR", flag: countryFlag.EE },
    EG: { code: "EG", name: "Єгипет", currency: "EGP", flag: countryFlag.EG },
    EH: {
      code: "EH",
      name: "Західна Сахара",
      currency: "MAD",
      flag: countryFlag.EH,
    },
    ER: { code: "ER", name: "Еритрея", currency: "ERN", flag: countryFlag.ER },
    ES: { code: "ES", name: "Іспанія", currency: "EUR", flag: countryFlag.ES },
    ET: { code: "ET", name: "Ефіопія", currency: "ETB", flag: countryFlag.ET },
    FI: {
      code: "FI",
      name: "Фінляндія",
      currency: "EUR",
      flag: countryFlag.FI,
    },
    FJ: { code: "FJ", name: "Фіджі", currency: "FJD", flag: countryFlag.FJ },
    FK: {
      code: "FK",
      name: "Фолклендські (Мальвінські) Острови",
      currency: "FKP",
      flag: countryFlag.FK,
    },
    FM: {
      code: "FM",
      name: "Мікронезія (Федеративні Штати)",
      currency: "USD",
      flag: countryFlag.FM,
    },
    FO: {
      code: "FO",
      name: "Фарерські Острови",
      currency: "DKK",
      flag: countryFlag.FO,
    },
    FR: { code: "FR", name: "Франція", currency: "EUR", flag: countryFlag.FR },
    GA: { code: "GA", name: "Габон", currency: "XAF", flag: countryFlag.GA },
    GB: {
      code: "GB",
      name: "Сполучене Королівство Великої Британії та Північної Ірландії",
      currency: "GBP",
      flag: countryFlag.GB,
    },
    GD: { code: "GD", name: "Гренада", currency: "XCD", flag: countryFlag.GD },
    GE: { code: "GE", name: "Грузія", currency: "GEL", flag: countryFlag.GE },
    GF: {
      code: "GF",
      name: "Французька Гвіана",
      currency: "EUR",
      flag: countryFlag.GF,
    },
    GG: { code: "GG", name: "Гернсі", currency: "GBP", flag: countryFlag.GG },
    GH: { code: "GH", name: "Гана", currency: "GHS", flag: countryFlag.GH },
    GI: {
      code: "GI",
      name: "Гібралтар",
      currency: "GIP",
      flag: countryFlag.GI,
    },
    GL: {
      code: "GL",
      name: "Гренландія",
      currency: "DKK",
      flag: countryFlag.GL,
    },
    GM: { code: "GM", name: "Гамбія", currency: "GMD", flag: countryFlag.GM },
    GN: { code: "GN", name: "Гвінея", currency: "GNF", flag: countryFlag.GN },
    GR: { code: "GR", name: "Греція", currency: "EUR", flag: countryFlag.GR },
    GS: {
      code: "GS",
      name: "Південна Джорджія та Південні Сандвічеві Острови",
      currency: "GBP",
      flag: countryFlag.GS,
    },
    GT: {
      code: "GT",
      name: "Гватемала",
      currency: "GTQ",
      flag: countryFlag.GT,
    },
    GU: { code: "GU", name: "Гуам", currency: "USD", flag: countryFlag.GU },
    GW: {
      code: "GW",
      name: "Гвінея-Бісау",
      currency: "XOF",
      flag: countryFlag.GW,
    },
    GY: { code: "GY", name: "Гаяна", currency: "GYD", flag: countryFlag.GY },
    HK: { code: "HK", name: "Гонконг", currency: "HKD", flag: countryFlag.HK },
    HM: {
      code: "HM",
      name: "Острів Херд і Острови Макдональд",
      currency: "AUD",
      flag: countryFlag.HM,
    },
    HN: { code: "HN", name: "Гондурас", currency: "HNL", flag: countryFlag.HN },
    HR: { code: "HR", name: "Хорватія", currency: "EUR", flag: countryFlag.HR },
    HT: { code: "HT", name: "Гаїті", currency: "HTG", flag: countryFlag.HT },
    HU: { code: "HU", name: "Угорщина", currency: "HUF", flag: countryFlag.HU },
    ID: {
      code: "ID",
      name: "Індонезія",
      currency: "IDR",
      flag: countryFlag.ID,
    },
    IE: { code: "IE", name: "Ірландія", currency: "EUR", flag: countryFlag.IE },
    IL: { code: "IL", name: "Ізраїль", currency: "ILS", flag: countryFlag.IL },
    IM: {
      code: "IM",
      name: "Острів Мен",
      currency: "GBP",
      flag: countryFlag.IM,
    },
    IN: { code: "IN", name: "Індія", currency: "INR", flag: countryFlag.IN },
    IO: {
      code: "IO",
      name: "Британська територія в Індійському океані",
      currency: "USD",
      flag: countryFlag.IO,
    },
    IQ: { code: "IQ", name: "Ірак", currency: "IQD", flag: countryFlag.IQ },
    IR: {
      code: "IR",
      name: "Іран (Ісламська Республіка)",
      currency: "IRR",
      flag: countryFlag.IR,
    },
    IS: { code: "IS", name: "Ісландія", currency: "ISK", flag: countryFlag.IS },
    IT: { code: "IT", name: "Італія", currency: "EUR", flag: countryFlag.IT },
    JE: { code: "JE", name: "Джерсі", currency: "GBP", flag: countryFlag.JE },
    JM: { code: "JM", name: "Ямайка", currency: "JMD", flag: countryFlag.JM },
    JO: { code: "JO", name: "Йорданія", currency: "JOD", flag: countryFlag.JO },
    JP: { code: "JP", name: "Японія", currency: "JPY", flag: countryFlag.JP },
    KE: { code: "KE", name: "Кенія", currency: "KES", flag: countryFlag.KE },
    KG: {
      code: "KG",
      name: "Киргизстан",
      currency: "KGS",
      flag: countryFlag.KG,
    },
    KH: { code: "KH", name: "Камбоджа", currency: "KHR", flag: countryFlag.KH },
    KI: { code: "KI", name: "Кірибаті", currency: "AUD", flag: countryFlag.KI },
    KM: {
      code: "KM",
      name: "Коморські Острови",
      currency: "KMF",
      flag: countryFlag.KM,
    },
    KN: {
      code: "KN",
      name: "Сент-Кітс і Невіс",
      currency: "XCD",
      flag: countryFlag.KN,
    },
    KP: {
      code: "KP",
      name: "Корея (Корейська Народно-Демократична Республіка)",
      currency: "KPW",
      flag: countryFlag.KP,
    },
    KR: {
      code: "KR",
      name: "Корея, Республіка",
      currency: "KRW",
      flag: countryFlag.KR,
    },
    KW: { code: "KW", name: "Кувейт", currency: "KWD", flag: countryFlag.KW },
    KY: {
      code: "KY",
      name: "Кайманові Острови",
      currency: "KYD",
      flag: countryFlag.KY,
    },
    KZ: {
      code: "KZ",
      name: "Казахстан",
      currency: "KZT",
      flag: countryFlag.KZ,
    },
    LA: {
      code: "LA",
      name: "Лаоська Народно-Демократична Республіка",
      currency: "LAK",
      flag: countryFlag.LA,
    },
    LB: { code: "LB", name: "Ліван", currency: "LBP", flag: countryFlag.LB },
    LC: {
      code: "LC",
      name: "Сент-Люсія",
      currency: "XCD",
      flag: countryFlag.LC,
    },
    LI: {
      code: "LI",
      name: "Ліхтенштейн",
      currency: "CHF",
      flag: countryFlag.LI,
    },
    LK: {
      code: "LK",
      name: "Шрі-Ланка",
      currency: "LKR",
      flag: countryFlag.LK,
    },
    LR: { code: "LR", name: "Ліберія", currency: "LRD", flag: countryFlag.LR },
    LS: { code: "LS", name: "Лесото", currency: "LSL", flag: countryFlag.LS },
    LT: { code: "LT", name: "Литва", currency: "EUR", flag: countryFlag.LT },
    LU: {
      code: "LU",
      name: "Люксембург",
      currency: "EUR",
      flag: countryFlag.LU,
    },
    LV: { code: "LV", name: "Латвія", currency: "EUR", flag: countryFlag.LV },
    LY: { code: "LY", name: "Лівія", currency: "LYD", flag: countryFlag.LY },
    MA: { code: "MA", name: "Марокко", currency: "MAD", flag: countryFlag.MA },
    MC: { code: "MC", name: "Монако", currency: "EUR", flag: countryFlag.MC },
    MD: {
      code: "MD",
      name: "Молдова, Республіка",
      currency: "MDL",
      flag: countryFlag.MD,
    },
    ME: {
      code: "ME",
      name: "Чорногорія",
      currency: "EUR",
      flag: countryFlag.ME,
    },
    MF: {
      code: "MF",
      name: "Сен-Мартен (Французька частина)",
      currency: "EUR",
      flag: countryFlag.MF,
    },
    MG: {
      code: "MG",
      name: "Мадагаскар",
      currency: "MGA",
      flag: countryFlag.MG,
    },
    MH: {
      code: "MH",
      name: "Маршаллові Острови",
      currency: "USD",
      flag: countryFlag.MH,
    },
    MK: {
      code: "MK",
      name: "Північна Македонія",
      currency: "MKD",
      flag: countryFlag.MK,
    },
    ML: { code: "ML", name: "Малі", currency: "XOF", flag: countryFlag.ML },
    MM: { code: "MM", name: "М'янма", currency: "MMK", flag: countryFlag.MM },
    MN: { code: "MN", name: "Монголія", currency: "MNT", flag: countryFlag.MN },
    MO: { code: "MO", name: "Макао", currency: "MOP", flag: countryFlag.MO },
    MP: {
      code: "MP",
      name: "Північні Маріанські Острови",
      currency: "USD",
      flag: countryFlag.MP,
    },
    MQ: {
      code: "MQ",
      name: "Мартініка",
      currency: "EUR",
      flag: countryFlag.MQ,
    },
    MR: {
      code: "MR",
      name: "Мавританія",
      currency: "MRU",
      flag: countryFlag.MR,
    },
    MS: {
      code: "MS",
      name: "Монтсеррат",
      currency: "XCD",
      flag: countryFlag.MS,
    },
    MT: { code: "MT", name: "Мальта", currency: "EUR", flag: countryFlag.MT },
    MU: { code: "MU", name: "Маврикій", currency: "MUR", flag: countryFlag.MU },
    MV: { code: "MV", name: "Мальдіви", currency: "MVR", flag: countryFlag.MV },
    MW: { code: "MW", name: "Малаві", currency: "MWK", flag: countryFlag.MW },
    MX: { code: "MX", name: "Мексика", currency: "MXN", flag: countryFlag.MX },
    MY: { code: "MY", name: "Малайзія", currency: "MYR", flag: countryFlag.MY },
    MZ: { code: "MZ", name: "Мозамбік", currency: "MZN", flag: countryFlag.MZ },
    NA: { code: "NA", name: "Намібія", currency: "NAD", flag: countryFlag.NA },
    NC: {
      code: "NC",
      name: "Нова Каледонія",
      currency: "XPF",
      flag: countryFlag.NC,
    },
    NE: { code: "NE", name: "Нігер", currency: "XOF", flag: countryFlag.NE },
    NF: {
      code: "NF",
      name: "Острів Норфолк",
      currency: "AUD",
      flag: countryFlag.NF,
    },
    NG: { code: "NG", name: "Нігерія", currency: "NGN", flag: countryFlag.NG },
    NI: {
      code: "NI",
      name: "Нікарагуа",
      currency: "NIO",
      flag: countryFlag.NI,
    },
    NL: {
      code: "NL",
      name: "Нідерланди",
      currency: "EUR",
      flag: countryFlag.NL,
    },
    NO: { code: "NO", name: "Норвегія", currency: "NOK", flag: countryFlag.NO },
    NP: { code: "NP", name: "Непал", currency: "NPR", flag: countryFlag.NP },
    NR: { code: "NR", name: "Науру", currency: "AUD", flag: countryFlag.NR },
    NU: { code: "NU", name: "Ніуе", currency: "NZD", flag: countryFlag.NU },
    NZ: {
      code: "NZ",
      name: "Нова Зеландія",
      currency: "NZD",
      flag: countryFlag.NZ,
    },
    OM: { code: "OM", name: "Оман", currency: "OMR", flag: countryFlag.OM },
    PA: { code: "PA", name: "Панама", currency: "PAB", flag: countryFlag.PA },
    PE: { code: "PE", name: "Перу", currency: "PEN", flag: countryFlag.PE },
    PF: {
      code: "PF",
      name: "Французька Полінезія",
      currency: "XPF",
      flag: countryFlag.PF,
    },
    PG: {
      code: "PG",
      name: "Папуа Нова Гвінея",
      currency: "PGK",
      flag: countryFlag.PG,
    },
    PH: {
      code: "PH",
      name: "Філіппіни",
      currency: "PHP",
      flag: countryFlag.PH,
    },
    PK: { code: "PK", name: "Пакистан", currency: "PKR", flag: countryFlag.PK },
    PL: { code: "PL", name: "Польща", currency: "PLN", flag: countryFlag.PL },
    PM: {
      code: "PM",
      name: "Сен-П'єр і Мікелон",
      currency: "EUR",
      flag: countryFlag.PM,
    },
    PN: { code: "PN", name: "Піткерн", currency: "NZD", flag: countryFlag.PN },
    PR: {
      code: "PR",
      name: "Пуерто-Ріко",
      currency: "USD",
      flag: countryFlag.PR,
    },
    PS: {
      code: "PS",
      name: "Держава Палестина",
      currency: "ILS",
      flag: countryFlag.PS,
    },
    PT: {
      code: "PT",
      name: "Португалія",
      currency: "EUR",
      flag: countryFlag.PT,
    },
    PW: { code: "PW", name: "Палау", currency: "USD", flag: countryFlag.PW },
    PY: { code: "PY", name: "Парагвай", currency: "PYG", flag: countryFlag.PY },
    QA: { code: "QA", name: "Катар", currency: "QAR", flag: countryFlag.QA },
    RE: { code: "RE", name: "Реюньйон", currency: "EUR", flag: countryFlag.RE },
    RO: { code: "RO", name: "Румунія", currency: "RON", flag: countryFlag.RO },
    RS: { code: "RS", name: "Сербія", currency: "RSD", flag: countryFlag.RS },
    RU: { code: "RU", name: "Росія", currency: "RUB", flag: countryFlag.RU },
    RW: { code: "RW", name: "Руанда", currency: "RWF", flag: countryFlag.RW },
    SA: {
      code: "SA",
      name: "Саудівська Аравія",
      currency: "SAR",
      flag: countryFlag.SA,
    },
    SB: {
      code: "SB",
      name: "Соломонові Острови",
      currency: "SBD",
      flag: countryFlag.SB,
    },
    SC: {
      code: "SC",
      name: "Сейшельські Острови",
      currency: "SCR",
      flag: countryFlag.SC,
    },
    SD: { code: "SD", name: "Судан", currency: "SDG", flag: countryFlag.SD },
    SE: { code: "SE", name: "Швеція", currency: "SEK", flag: countryFlag.SE },
    SG: { code: "SG", name: "Сінгапур", currency: "SGD", flag: countryFlag.SG },
    SH: {
      code: "SH",
      name: "Острів Святої Єлени, Вознесіння і Тристан-да-Кунья",
      currency: "SHP",
      flag: countryFlag.SH,
    },
    SI: { code: "SI", name: "Словенія", currency: "EUR", flag: countryFlag.SI },
    SJ: {
      code: "SJ",
      name: "Шпіцберген і Ян-Маєн",
      currency: "NOK",
      flag: countryFlag.SJ,
    },
    SK: {
      code: "SK",
      name: "Словаччина",
      currency: "EUR",
      flag: countryFlag.SK,
    },
    SL: {
      code: "SL",
      name: "Сьєрра-Леоне",
      currency: "SLL",
      flag: countryFlag.SL,
    },
    SM: {
      code: "SM",
      name: "Сан-Марино",
      currency: "EUR",
      flag: countryFlag.SM,
    },
    SN: { code: "SN", name: "Сенегал", currency: "XOF", flag: countryFlag.SN },
    SO: { code: "SO", name: "Сомалі", currency: "SOS", flag: countryFlag.SO },
    SR: { code: "SR", name: "Суринам", currency: "SRD", flag: countryFlag.SR },
    SS: {
      code: "SS",
      name: "Південний Судан",
      currency: "SSP",
      flag: countryFlag.SS,
    },
    ST: {
      code: "ST",
      name: "Сан-Томе і Принсіпі",
      currency: "STN",
      flag: countryFlag.ST,
    },
    SV: {
      code: "SV",
      name: "Сальвадор",
      currency: "USD",
      flag: countryFlag.SV,
    },
    SX: {
      code: "SX",
      name: "Сінт-Мартен (Нідерландська частина)",
      currency: "ANG",
      flag: countryFlag.SX,
    },
    SY: {
      code: "SY",
      name: "Сирійська Арабська Республіка",
      currency: "SYP",
      flag: countryFlag.SY,
    },
    SZ: { code: "SZ", name: "Есватіні", currency: "SZL", flag: countryFlag.SZ },
    TC: {
      code: "TC",
      name: "Острови Теркс і Кайкос",
      currency: "USD",
      flag: countryFlag.TC,
    },
    TD: { code: "TD", name: "Чад", currency: "XAF", flag: countryFlag.TD },
    TF: {
      code: "TF",
      name: "Французькі Південні Території",
      currency: "EUR",
      flag: countryFlag.TF,
    },
    TG: { code: "TG", name: "Того", currency: "XOF", flag: countryFlag.TG },
    TH: { code: "TH", name: "Таїланд", currency: "THB", flag: countryFlag.TH },
    TJ: {
      code: "TJ",
      name: "Таджикистан",
      currency: "TJS",
      flag: countryFlag.TJ,
    },
    TK: { code: "TK", name: "Токелау", currency: "NZD", flag: countryFlag.TK },
    TL: {
      code: "TL",
      name: "Тімор-Лешті",
      currency: "USD",
      flag: countryFlag.TL,
    },
    TM: {
      code: "TM",
      name: "Туркменістан",
      currency: "TMT",
      flag: countryFlag.TM,
    },
    TN: { code: "TN", name: "Туніс", currency: "TND", flag: countryFlag.TN },
    TO: { code: "TO", name: "Тонга", currency: "TOP", flag: countryFlag.TO },
    TR: {
      code: "TR",
      name: "Туреччина",
      currency: "TRY",
      flag: countryFlag.TR,
    },
    TT: {
      code: "TT",
      name: "Тринідад і Тобаго",
      currency: "TTD",
      flag: countryFlag.TT,
    },
    TV: { code: "TV", name: "Тувалу", currency: "AUD", flag: countryFlag.TV },
    TW: {
      code: "TW",
      name: "Тайвань, провінція Китаю",
      currency: "TWD",
      flag: countryFlag.TW,
    },
    TZ: {
      code: "TZ",
      name: "Танзанія, Об'єднана Республіка",
      currency: "TZS",
      flag: countryFlag.TZ,
    },
    UA: { code: "UA", name: "Україна", currency: "UAH", flag: countryFlag.UA },
    UG: { code: "UG", name: "Уганда", currency: "UGX", flag: countryFlag.UG },
    UM: {
      code: "UM",
      name: "Зовнішні малі острови (США)",
      currency: "USD",
      flag: countryFlag.UM,
    },
    US: {
      code: "US",
      name: "Сполучені Штати Америки",
      currency: "USD",
      flag: countryFlag.US,
    },
    UY: { code: "UY", name: "Уругвай", currency: "UYU", flag: countryFlag.UY },
    UZ: {
      code: "UZ",
      name: "Узбекистан",
      currency: "UZS",
      flag: countryFlag.UZ,
    },
    VA: {
      code: "VA",
      name: "Святий Престол",
      currency: "EUR",
      flag: countryFlag.VA,
    },
    VC: {
      code: "VC",
      name: "Сент-Вінсент і Гренадіни",
      currency: "XCD",
      flag: countryFlag.VC,
    },
    VE: {
      code: "VE",
      name: "Венесуела (Боліваріанська Республіка)",
      currency: "VES",
      flag: countryFlag.VE,
    },
    VG: {
      code: "VG",
      name: "Віргінські Острови (Британські)",
      currency: "USD",
      flag: countryFlag.VG,
    },
    VI: {
      code: "VI",
      name: "Віргінські Острови (США)",
      currency: "USD",
      flag: countryFlag.VI,
    },
    VN: { code: "VN", name: "В'єтнам", currency: "VND", flag: countryFlag.VN },
    VU: { code: "VU", name: "Вануату", currency: "VUV", flag: countryFlag.VU },
    WF: {
      code: "WF",
      name: "Уолліс і Футуна",
      currency: "XPF",
      flag: countryFlag.WF,
    },
    WS: { code: "WS", name: "Самоа", currency: "WST", flag: countryFlag.WS },
    YE: { code: "YE", name: "Ємен", currency: "YER", flag: countryFlag.YE },
    YT: { code: "YT", name: "Майотта", currency: "EUR", flag: countryFlag.YT },
    ZA: {
      code: "ZA",
      name: "Південна Африка",
      currency: "ZAR",
      flag: countryFlag.ZA,
    },
    ZM: { code: "ZM", name: "Замбія", currency: "ZMW", flag: countryFlag.ZM },
    ZW: { code: "ZW", name: "Зімбабве", currency: "ZWL", flag: countryFlag.ZW },
  },
  ru: {
    AD: { code: "AD", name: "Андорра", currency: "EUR", flag: countryFlag.AD },
    AE: {
      code: "AE",
      name: "Объединенные Арабские Эмираты",
      currency: "AED",
      flag: countryFlag.AE,
    },
    AF: {
      code: "AF",
      name: "Афганистан",
      currency: "AFN",
      flag: countryFlag.AF,
    },
    AG: {
      code: "AG",
      name: "Антигуа и Барбуда",
      currency: "XCD",
      flag: countryFlag.AG,
    },
    AI: { code: "AI", name: "Ангилья", currency: "XCD", flag: countryFlag.AI },
    AL: { code: "AL", name: "Албания", currency: "ALL", flag: countryFlag.AL },
    AM: { code: "AM", name: "Армения", currency: "AMD", flag: countryFlag.AM },
    AO: { code: "AO", name: "Ангола", currency: "AOA", flag: countryFlag.AO },
    AQ: { code: "AQ", name: "Антарктида", currency: "", flag: countryFlag.AQ },
    AR: {
      code: "AR",
      name: "Аргентина",
      currency: "ARS",
      flag: countryFlag.AR,
    },
    AS: {
      code: "AS",
      name: "Американское Самоа",
      currency: "USD",
      flag: countryFlag.AS,
    },
    AT: { code: "AT", name: "Австрия", currency: "EUR", flag: countryFlag.AT },
    AU: {
      code: "AU",
      name: "Австралия",
      currency: "AUD",
      flag: countryFlag.AU,
    },
    AW: { code: "AW", name: "Аруба", currency: "AWG", flag: countryFlag.AW },
    AX: {
      code: "AX",
      name: "Аландские острова",
      currency: "EUR",
      flag: countryFlag.AX,
    },
    AZ: {
      code: "AZ",
      name: "Азербайджан",
      currency: "AZN",
      flag: countryFlag.AZ,
    },
    BA: {
      code: "BA",
      name: "Босния и Герцеговина",
      currency: "BAM",
      flag: countryFlag.BA,
    },
    BB: { code: "BB", name: "Барбадос", currency: "BBD", flag: countryFlag.BB },
    BD: {
      code: "BD",
      name: "Бангладеш",
      currency: "BDT",
      flag: countryFlag.BD,
    },
    BE: { code: "BE", name: "Бельгия", currency: "EUR", flag: countryFlag.BE },
    BF: {
      code: "BF",
      name: "Буркина-Фасо",
      currency: "XOF",
      flag: countryFlag.BF,
    },
    BG: { code: "BG", name: "Болгария", currency: "BGN", flag: countryFlag.BG },
    BH: { code: "BH", name: "Бахрейн", currency: "BHD", flag: countryFlag.BH },
    BI: { code: "BI", name: "Бурунди", currency: "BIF", flag: countryFlag.BI },
    BJ: { code: "BJ", name: "Бенин", currency: "XOF", flag: countryFlag.BJ },
    BL: {
      code: "BL",
      name: "Сен-Бартелеми",
      currency: "EUR",
      flag: countryFlag.BL,
    },
    BM: {
      code: "BM",
      name: "Бермудские Острова",
      currency: "BMD",
      flag: countryFlag.BM,
    },
    BN: {
      code: "BN",
      name: "Бруней-Даруссалам",
      currency: "BND",
      flag: countryFlag.BN,
    },
    BO: {
      code: "BO",
      name: "Боливия (Многонациональное Государство)",
      currency: "BOB",
      flag: countryFlag.BO,
    },
    BQ: {
      code: "BQ",
      name: "Бонэйр, Синт-Эстатиус и Саба",
      currency: "USD",
      flag: countryFlag.BQ,
    },
    BR: { code: "BR", name: "Бразилия", currency: "BRL", flag: countryFlag.BR },
    BS: {
      code: "BS",
      name: "Багамские Острова",
      currency: "BSD",
      flag: countryFlag.BS,
    },
    BT: { code: "BT", name: "Бутан", currency: "BTN", flag: countryFlag.BT },
    BV: {
      code: "BV",
      name: "Остров Буве",
      currency: "NOK",
      flag: countryFlag.BV,
    },
    BW: { code: "BW", name: "Ботсвана", currency: "BWP", flag: countryFlag.BW },
    BY: { code: "BY", name: "Беларусь", currency: "BYN", flag: countryFlag.BY },
    BZ: { code: "BZ", name: "Белиз", currency: "BZD", flag: countryFlag.BZ },
    CA: { code: "CA", name: "Канада", currency: "CAD", flag: countryFlag.CA },
    CC: {
      code: "CC",
      name: "Кокосовые (Килинг) Острова",
      currency: "AUD",
      flag: countryFlag.CC,
    },
    CD: {
      code: "CD",
      name: "Конго, Демократическая Республика",
      currency: "CDF",
      flag: countryFlag.CD,
    },
    CF: {
      code: "CF",
      name: "Центральноафриканская Республика",
      currency: "XAF",
      flag: countryFlag.CF,
    },
    CG: { code: "CG", name: "Конго", currency: "XAF", flag: countryFlag.CG },
    CH: {
      code: "CH",
      name: "Швейцария",
      currency: "CHF",
      flag: countryFlag.CH,
    },
    CI: {
      code: "CI",
      name: "Кот-д'Ивуар",
      currency: "XOF",
      flag: countryFlag.CI,
    },
    CK: {
      code: "CK",
      name: "Острова Кука",
      currency: "NZD",
      flag: countryFlag.CK,
    },
    CL: { code: "CL", name: "Чили", currency: "CLP", flag: countryFlag.CL },
    CM: { code: "CM", name: "Камерун", currency: "XAF", flag: countryFlag.CM },
    CN: { code: "CN", name: "Китай", currency: "CNY", flag: countryFlag.CN },
    CO: { code: "CO", name: "Колумбия", currency: "COP", flag: countryFlag.CO },
    CR: {
      code: "CR",
      name: "Коста-Рика",
      currency: "CRC",
      flag: countryFlag.CR,
    },
    CU: { code: "CU", name: "Куба", currency: "CUP", flag: countryFlag.CU },
    CV: {
      code: "CV",
      name: "Кабо-Верде",
      currency: "CVE",
      flag: countryFlag.CV,
    },
    CW: { code: "CW", name: "Кюрасао", currency: "ANG", flag: countryFlag.CW },
    CX: {
      code: "CX",
      name: "Остров Рождества",
      currency: "AUD",
      flag: countryFlag.CX,
    },
    CY: { code: "CY", name: "Кипр", currency: "EUR", flag: countryFlag.CY },
    CZ: { code: "CZ", name: "Чехия", currency: "CZK", flag: countryFlag.CZ },
    DE: { code: "DE", name: "Германия", currency: "EUR", flag: countryFlag.DE },
    DJ: { code: "DJ", name: "Джибути", currency: "DJF", flag: countryFlag.DJ },
    DK: { code: "DK", name: "Дания", currency: "DKK", flag: countryFlag.DK },
    DM: { code: "DM", name: "Доминика", currency: "XCD", flag: countryFlag.DM },
    DO: {
      code: "DO",
      name: "Доминиканская Республика",
      currency: "DOP",
      flag: countryFlag.DO,
    },
    DZ: { code: "DZ", name: "Алжир", currency: "DZD", flag: countryFlag.DZ },
    EC: { code: "EC", name: "Эквадор", currency: "USD", flag: countryFlag.EC },
    EE: { code: "EE", name: "Эстония", currency: "EUR", flag: countryFlag.EE },
    EG: { code: "EG", name: "Египет", currency: "EGP", flag: countryFlag.EG },
    EH: {
      code: "EH",
      name: "Западная Сахара",
      currency: "MAD",
      flag: countryFlag.EH,
    },
    ER: { code: "ER", name: "Эритрея", currency: "ERN", flag: countryFlag.ER },
    ES: { code: "ES", name: "Испания", currency: "EUR", flag: countryFlag.ES },
    ET: { code: "ET", name: "Эфиопия", currency: "ETB", flag: countryFlag.ET },
    FI: {
      code: "FI",
      name: "Финляндия",
      currency: "EUR",
      flag: countryFlag.FI,
    },
    FJ: { code: "FJ", name: "Фиджи", currency: "FJD", flag: countryFlag.FJ },
    FK: {
      code: "FK",
      name: "Фолклендские (Мальвинские) Острова",
      currency: "FKP",
      flag: countryFlag.FK,
    },
    FM: {
      code: "FM",
      name: "Микронезия (Федеративные Штаты)",
      currency: "USD",
      flag: countryFlag.FM,
    },
    FO: {
      code: "FO",
      name: "Фарерские Острова",
      currency: "DKK",
      flag: countryFlag.FO,
    },
    FR: { code: "FR", name: "Франция", currency: "EUR", flag: countryFlag.FR },
    GA: { code: "GA", name: "Габон", currency: "XAF", flag: countryFlag.GA },
    GB: {
      code: "GB",
      name: "Соединенное Королевство Великобритании и Северной Ирландии",
      currency: "GBP",
      flag: countryFlag.GB,
    },
    GD: { code: "GD", name: "Гренада", currency: "XCD", flag: countryFlag.GD },
    GE: { code: "GE", name: "Грузия", currency: "GEL", flag: countryFlag.GE },
    GF: {
      code: "GF",
      name: "Французская Гвиана",
      currency: "EUR",
      flag: countryFlag.GF,
    },
    GG: { code: "GG", name: "Гернси", currency: "GBP", flag: countryFlag.GG },
    GH: { code: "GH", name: "Гана", currency: "GHS", flag: countryFlag.GH },
    GI: {
      code: "GI",
      name: "Гибралтар",
      currency: "GIP",
      flag: countryFlag.GI,
    },
    GL: {
      code: "GL",
      name: "Гренландия",
      currency: "DKK",
      flag: countryFlag.GL,
    },
    GM: { code: "GM", name: "Гамбия", currency: "GMD", flag: countryFlag.GM },
    GN: { code: "GN", name: "Гвинея", currency: "GNF", flag: countryFlag.GN },
    GR: { code: "GR", name: "Греция", currency: "EUR", flag: countryFlag.GR },
    GS: {
      code: "GS",
      name: "Южная Георгия и Южные Сандвичевы Острова",
      currency: "GBP",
      flag: countryFlag.GS,
    },
    GT: {
      code: "GT",
      name: "Гватемала",
      currency: "GTQ",
      flag: countryFlag.GT,
    },
    GU: { code: "GU", name: "Гуам", currency: "USD", flag: countryFlag.GU },
    GW: {
      code: "GW",
      name: "Гвинея-Бисау",
      currency: "XOF",
      flag: countryFlag.GW,
    },
    GY: { code: "GY", name: "Гайана", currency: "GYD", flag: countryFlag.GY },
    HK: { code: "HK", name: "Гонконг", currency: "HKD", flag: countryFlag.HK },
    HM: {
      code: "HM",
      name: "Остров Херд и Острова Макдональд",
      currency: "AUD",
      flag: countryFlag.HM,
    },
    HN: { code: "HN", name: "Гондурас", currency: "HNL", flag: countryFlag.HN },
    HR: { code: "HR", name: "Хорватия", currency: "EUR", flag: countryFlag.HR },
    HT: { code: "HT", name: "Гаити", currency: "HTG", flag: countryFlag.HT },
    HU: { code: "HU", name: "Венгрия", currency: "HUF", flag: countryFlag.HU },
    ID: {
      code: "ID",
      name: "Индонезия",
      currency: "IDR",
      flag: countryFlag.ID,
    },
    IE: { code: "IE", name: "Ирландия", currency: "EUR", flag: countryFlag.IE },
    IL: { code: "IL", name: "Израиль", currency: "ILS", flag: countryFlag.IL },
    IM: {
      code: "IM",
      name: "Остров Мэн",
      currency: "GBP",
      flag: countryFlag.IM,
    },
    IN: { code: "IN", name: "Индия", currency: "INR", flag: countryFlag.IN },
    IO: {
      code: "IO",
      name: "Британская территория в Индийском океане",
      currency: "USD",
      flag: countryFlag.IO,
    },
    IQ: { code: "IQ", name: "Ирак", currency: "IQD", flag: countryFlag.IQ },
    IR: {
      code: "IR",
      name: "Иран (Исламская Республика)",
      currency: "IRR",
      flag: countryFlag.IR,
    },
    IS: { code: "IS", name: "Исландия", currency: "ISK", flag: countryFlag.IS },
    IT: { code: "IT", name: "Италия", currency: "EUR", flag: countryFlag.IT },
    JE: { code: "JE", name: "Джерси", currency: "GBP", flag: countryFlag.JE },
    JM: { code: "JM", name: "Ямайка", currency: "JMD", flag: countryFlag.JM },
    JO: { code: "JO", name: "Иордания", currency: "JOD", flag: countryFlag.JO },
    JP: { code: "JP", name: "Япония", currency: "JPY", flag: countryFlag.JP },
    KE: { code: "KE", name: "Кения", currency: "KES", flag: countryFlag.KE },
    KG: {
      code: "KG",
      name: "Кыргызстан",
      currency: "KGS",
      flag: countryFlag.KG,
    },
    KH: { code: "KH", name: "Камбоджа", currency: "KHR", flag: countryFlag.KH },
    KI: { code: "KI", name: "Кирибати", currency: "AUD", flag: countryFlag.KI },
    KM: {
      code: "KM",
      name: "Коморские Острова",
      currency: "KMF",
      flag: countryFlag.KM,
    },
    KN: {
      code: "KN",
      name: "Сент-Китс и Невис",
      currency: "XCD",
      flag: countryFlag.KN,
    },
    KP: {
      code: "KP",
      name: "Корея (Корейская Народно-Демократическая Республика)",
      currency: "KPW",
      flag: countryFlag.KP,
    },
    KR: {
      code: "KR",
      name: "Корея, Республика",
      currency: "KRW",
      flag: countryFlag.KR,
    },
    KW: { code: "KW", name: "Кувейт", currency: "KWD", flag: countryFlag.KW },
    KY: {
      code: "KY",
      name: "Каймановы Острова",
      currency: "KYD",
      flag: countryFlag.KY,
    },
    KZ: {
      code: "KZ",
      name: "Казахстан",
      currency: "KZT",
      flag: countryFlag.KZ,
    },
    LA: {
      code: "LA",
      name: "Лаосская Народно-Демократическая Республика",
      currency: "LAK",
      flag: countryFlag.LA,
    },
    LB: { code: "LB", name: "Ливан", currency: "LBP", flag: countryFlag.LB },
    LC: {
      code: "LC",
      name: "Сент-Люсия",
      currency: "XCD",
      flag: countryFlag.LC,
    },
    LI: {
      code: "LI",
      name: "Лихтенштейн",
      currency: "CHF",
      flag: countryFlag.LI,
    },
    LK: {
      code: "LK",
      name: "Шри-Ланка",
      currency: "LKR",
      flag: countryFlag.LK,
    },
    LR: { code: "LR", name: "Либерия", currency: "LRD", flag: countryFlag.LR },
    LS: { code: "LS", name: "Лесото", currency: "LSL", flag: countryFlag.LS },
    LT: { code: "LT", name: "Литва", currency: "EUR", flag: countryFlag.LT },
    LU: {
      code: "LU",
      name: "Люксембург",
      currency: "EUR",
      flag: countryFlag.LU,
    },
    LV: { code: "LV", name: "Латвия", currency: "EUR", flag: countryFlag.LV },
    LY: { code: "LY", name: "Ливия", currency: "LYD", flag: countryFlag.LY },
    MA: { code: "MA", name: "Марокко", currency: "MAD", flag: countryFlag.MA },
    MC: { code: "MC", name: "Монако", currency: "EUR", flag: countryFlag.MC },
    MD: {
      code: "MD",
      name: "Молдова, Республика",
      currency: "MDL",
      flag: countryFlag.MD,
    },
    ME: {
      code: "ME",
      name: "Черногория",
      currency: "EUR",
      flag: countryFlag.ME,
    },
    MF: {
      code: "MF",
      name: "Сен-Мартен (Французская часть)",
      currency: "EUR",
      flag: countryFlag.MF,
    },
    MG: {
      code: "MG",
      name: "Мадагаскар",
      currency: "MGA",
      flag: countryFlag.MG,
    },
    MH: {
      code: "MH",
      name: "Маршалловы Острова",
      currency: "USD",
      flag: countryFlag.MH,
    },
    MK: {
      code: "MK",
      name: "Северная Македония",
      currency: "MKD",
      flag: countryFlag.MK,
    },
    ML: { code: "ML", name: "Мали", currency: "XOF", flag: countryFlag.ML },
    MM: { code: "MM", name: "Мьянма", currency: "MMK", flag: countryFlag.MM },
    MN: { code: "MN", name: "Монголия", currency: "MNT", flag: countryFlag.MN },
    MO: { code: "MO", name: "Макао", currency: "MOP", flag: countryFlag.MO },
    MP: {
      code: "MP",
      name: "Северные Марианские Острова",
      currency: "USD",
      flag: countryFlag.MP,
    },
    MQ: {
      code: "MQ",
      name: "Мартиника",
      currency: "EUR",
      flag: countryFlag.MQ,
    },
    MR: {
      code: "MR",
      name: "Мавритания",
      currency: "MRU",
      flag: countryFlag.MR,
    },
    MS: {
      code: "MS",
      name: "Монтсеррат",
      currency: "XCD",
      flag: countryFlag.MS,
    },
    MT: { code: "MT", name: "Мальта", currency: "EUR", flag: countryFlag.MT },
    MU: { code: "MU", name: "Маврикий", currency: "MUR", flag: countryFlag.MU },
    MV: { code: "MV", name: "Мальдивы", currency: "MVR", flag: countryFlag.MV },
    MW: { code: "MW", name: "Малави", currency: "MWK", flag: countryFlag.MW },
    MX: { code: "MX", name: "Мексика", currency: "MXN", flag: countryFlag.MX },
    MY: { code: "MY", name: "Малайзия", currency: "MYR", flag: countryFlag.MY },
    MZ: { code: "MZ", name: "Мозамбик", currency: "MZN", flag: countryFlag.MZ },
    NA: { code: "NA", name: "Намибия", currency: "NAD", flag: countryFlag.NA },
    NC: {
      code: "NC",
      name: "Новая Каледония",
      currency: "XPF",
      flag: countryFlag.NC,
    },
    NE: { code: "NE", name: "Нигер", currency: "XOF", flag: countryFlag.NE },
    NF: {
      code: "NF",
      name: "Остров Норфолк",
      currency: "AUD",
      flag: countryFlag.NF,
    },
    NG: { code: "NG", name: "Нигерия", currency: "NGN", flag: countryFlag.NG },
    NI: {
      code: "NI",
      name: "Никарагуа",
      currency: "NIO",
      flag: countryFlag.NI,
    },
    NL: {
      code: "NL",
      name: "Нидерланды",
      currency: "EUR",
      flag: countryFlag.NL,
    },
    NO: { code: "NO", name: "Норвегия", currency: "NOK", flag: countryFlag.NO },
    NP: { code: "NP", name: "Непал", currency: "NPR", flag: countryFlag.NP },
    NR: { code: "NR", name: "Науру", currency: "AUD", flag: countryFlag.NR },
    NU: { code: "NU", name: "Ниуэ", currency: "NZD", flag: countryFlag.NU },
    NZ: {
      code: "NZ",
      name: "Новая Зеландия",
      currency: "NZD",
      flag: countryFlag.NZ,
    },
    OM: { code: "OM", name: "Оман", currency: "OMR", flag: countryFlag.OM },
    PA: { code: "PA", name: "Панама", currency: "PAB", flag: countryFlag.PA },
    PE: { code: "PE", name: "Перу", currency: "PEN", flag: countryFlag.PE },
    PF: {
      code: "PF",
      name: "Французская Полинезия",
      currency: "XPF",
      flag: countryFlag.PF,
    },
    PG: {
      code: "PG",
      name: "Папуа — Новая Гвинея",
      currency: "PGK",
      flag: countryFlag.PG,
    },
    PH: {
      code: "PH",
      name: "Филиппины",
      currency: "PHP",
      flag: countryFlag.PH,
    },
    PK: { code: "PK", name: "Пакистан", currency: "PKR", flag: countryFlag.PK },
    PL: { code: "PL", name: "Польша", currency: "PLN", flag: countryFlag.PL },
    PM: {
      code: "PM",
      name: "Сен-Пьер и Микелон",
      currency: "EUR",
      flag: countryFlag.PM,
    },
    PN: { code: "PN", name: "Питкэрн", currency: "NZD", flag: countryFlag.PN },
    PR: {
      code: "PR",
      name: "Пуэрто-Рико",
      currency: "USD",
      flag: countryFlag.PR,
    },
    PS: {
      code: "PS",
      name: "Государство Палестина",
      currency: "ILS",
      flag: countryFlag.PS,
    },
    PT: {
      code: "PT",
      name: "Португалия",
      currency: "EUR",
      flag: countryFlag.PT,
    },
    PW: { code: "PW", name: "Палау", currency: "USD", flag: countryFlag.PW },
    PY: { code: "PY", name: "Парагвай", currency: "PYG", flag: countryFlag.PY },
    QA: { code: "QA", name: "Катар", currency: "QAR", flag: countryFlag.QA },
    RE: { code: "RE", name: "Реюньон", currency: "EUR", flag: countryFlag.RE },
    RO: { code: "RO", name: "Румыния", currency: "RON", flag: countryFlag.RO },
    RS: { code: "RS", name: "Сербия", currency: "RSD", flag: countryFlag.RS },
    RU: {
      code: "RU",
      name: "Российская Федерация",
      currency: "RUB",
      flag: countryFlag.RU,
    },
    RW: { code: "RW", name: "Руанда", currency: "RWF", flag: countryFlag.RW },
    SA: {
      code: "SA",
      name: "Саудовская Аравия",
      currency: "SAR",
      flag: countryFlag.SA,
    },
    SB: {
      code: "SB",
      name: "Соломоновы Острова",
      currency: "SBD",
      flag: countryFlag.SB,
    },
    SC: {
      code: "SC",
      name: "Сейшельские Острова",
      currency: "SCR",
      flag: countryFlag.SC,
    },
    SD: { code: "SD", name: "Судан", currency: "SDG", flag: countryFlag.SD },
    SE: { code: "SE", name: "Швеция", currency: "SEK", flag: countryFlag.SE },
    SG: { code: "SG", name: "Сингапур", currency: "SGD", flag: countryFlag.SG },
    SH: {
      code: "SH",
      name: "Остров Святой Елены, Вознесения и Тристан-да-Кунья",
      currency: "SHP",
      flag: countryFlag.SH,
    },
    SI: { code: "SI", name: "Словения", currency: "EUR", flag: countryFlag.SI },
    SJ: {
      code: "SJ",
      name: "Шпицберген и Ян-Майен",
      currency: "NOK",
      flag: countryFlag.SJ,
    },
    SK: { code: "SK", name: "Словакия", currency: "EUR", flag: countryFlag.SK },
    SL: {
      code: "SL",
      name: "Сьерра-Леоне",
      currency: "SLL",
      flag: countryFlag.SL,
    },
    SM: {
      code: "SM",
      name: "Сан-Марино",
      currency: "EUR",
      flag: countryFlag.SM,
    },
    SN: { code: "SN", name: "Сенегал", currency: "XOF", flag: countryFlag.SN },
    SO: { code: "SO", name: "Сомали", currency: "SOS", flag: countryFlag.SO },
    SR: { code: "SR", name: "Суринам", currency: "SRD", flag: countryFlag.SR },
    SS: {
      code: "SS",
      name: "Южный Судан",
      currency: "SSP",
      flag: countryFlag.SS,
    },
    ST: {
      code: "ST",
      name: "Сан-Томе и Принсипи",
      currency: "STN",
      flag: countryFlag.ST,
    },
    SV: {
      code: "SV",
      name: "Сальвадор",
      currency: "USD",
      flag: countryFlag.SV,
    },
    SX: {
      code: "SX",
      name: "Синт-Мартен (Нидерландская часть)",
      currency: "ANG",
      flag: countryFlag.SX,
    },
    SY: {
      code: "SY",
      name: "Сирийская Арабская Республика",
      currency: "SYP",
      flag: countryFlag.SY,
    },
    SZ: { code: "SZ", name: "Эсватини", currency: "SZL", flag: countryFlag.SZ },
    TC: {
      code: "TC",
      name: "Острова Теркс и Кайкос",
      currency: "USD",
      flag: countryFlag.TC,
    },
    TD: { code: "TD", name: "Чад", currency: "XAF", flag: countryFlag.TD },
    TF: {
      code: "TF",
      name: "Французские Южные территории",
      currency: "EUR",
      flag: countryFlag.TF,
    },
    TG: { code: "TG", name: "Того", currency: "XOF", flag: countryFlag.TG },
    TH: { code: "TH", name: "Таиланд", currency: "THB", flag: countryFlag.TH },
    TJ: {
      code: "TJ",
      name: "Таджикистан",
      currency: "TJS",
      flag: countryFlag.TJ,
    },
    TK: { code: "TK", name: "Токелау", currency: "NZD", flag: countryFlag.TK },
    TL: {
      code: "TL",
      name: "Тимор-Лешти",
      currency: "USD",
      flag: countryFlag.TL,
    },
    TM: {
      code: "TM",
      name: "Туркменистан",
      currency: "TMT",
      flag: countryFlag.TM,
    },
    TN: { code: "TN", name: "Тунис", currency: "TND", flag: countryFlag.TN },
    TO: { code: "TO", name: "Тонга", currency: "TOP", flag: countryFlag.TO },
    TR: { code: "TR", name: "Турция", currency: "TRY", flag: countryFlag.TR },
    TT: {
      code: "TT",
      name: "Тринидад и Тобаго",
      currency: "TTD",
      flag: countryFlag.TT,
    },
    TV: { code: "TV", name: "Тувалу", currency: "AUD", flag: countryFlag.TV },
    TW: {
      code: "TW",
      name: "Тайвань, провинция Китая",
      currency: "TWD",
      flag: countryFlag.TW,
    },
    TZ: {
      code: "TZ",
      name: "Танзания, Объединенная Республика",
      currency: "TZS",
      flag: countryFlag.TZ,
    },
    UA: { code: "UA", name: "Украина", currency: "UAH", flag: countryFlag.UA },
    UG: { code: "UG", name: "Уганда", currency: "UGX", flag: countryFlag.UG },
    UM: {
      code: "UM",
      name: "Внешние малые острова (США)",
      currency: "USD",
      flag: countryFlag.UM,
    },
    US: {
      code: "US",
      name: "Соединенные Штаты Америки",
      currency: "USD",
      flag: countryFlag.US,
    },
    UY: { code: "UY", name: "Уругвай", currency: "UYU", flag: countryFlag.UY },
    UZ: {
      code: "UZ",
      name: "Узбекистан",
      currency: "UZS",
      flag: countryFlag.UZ,
    },
    VA: {
      code: "VA",
      name: "Святой Престол",
      currency: "EUR",
      flag: countryFlag.VA,
    },
    VC: {
      code: "VC",
      name: "Сент-Винсент и Гренадины",
      currency: "XCD",
      flag: countryFlag.VC,
    },
    VE: {
      code: "VE",
      name: "Венесуэла (Боливарианская Республика)",
      currency: "VES",
      flag: countryFlag.VE,
    },
    VG: {
      code: "VG",
      name: "Виргинские Острова (Британские)",
      currency: "USD",
      flag: countryFlag.VG,
    },
    VI: {
      code: "VI",
      name: "Виргинские Острова (США)",
      currency: "USD",
      flag: countryFlag.VI,
    },
    VN: { code: "VN", name: "Вьетнам", currency: "VND", flag: countryFlag.VN },
    VU: { code: "VU", name: "Вануату", currency: "VUV", flag: countryFlag.VU },
    WF: {
      code: "WF",
      name: "Уоллис и Футуна",
      currency: "XPF",
      flag: countryFlag.WF,
    },
    WS: { code: "WS", name: "Самоа", currency: "WST", flag: countryFlag.WS },
    YE: { code: "YE", name: "Йемен", currency: "YER", flag: countryFlag.YE },
    YT: { code: "YT", name: "Майотта", currency: "EUR", flag: countryFlag.YT },
    ZA: {
      code: "ZA",
      name: "Южная Африка",
      currency: "ZAR",
      flag: countryFlag.ZA,
    },
    ZM: { code: "ZM", name: "Замбия", currency: "ZMW", flag: countryFlag.ZM },
    ZW: { code: "ZW", name: "Зимбабве", currency: "ZWL", flag: countryFlag.ZW },
  },
  en: {
    AD: { code: "AD", name: "Andorra", currency: "EUR", flag: countryFlag.AD },
    AE: {
      code: "AE",
      name: "United Arab Emirates",
      currency: "AED",
      flag: countryFlag.AE,
    },
    AF: {
      code: "AF",
      name: "Afghanistan",
      currency: "AFN",
      flag: countryFlag.AF,
    },
    AG: {
      code: "AG",
      name: "Antigua and Barbuda",
      currency: "XCD",
      flag: countryFlag.AG,
    },
    AI: { code: "AI", name: "Anguilla", currency: "XCD", flag: countryFlag.AI },
    AL: { code: "AL", name: "Albania", currency: "ALL", flag: countryFlag.AL },
    AM: { code: "AM", name: "Armenia", currency: "AMD", flag: countryFlag.AM },
    AO: { code: "AO", name: "Angola", currency: "AOA", flag: countryFlag.AO },
    AQ: { code: "AQ", name: "Antarctica", currency: "", flag: countryFlag.AQ },
    AR: {
      code: "AR",
      name: "Argentina",
      currency: "ARS",
      flag: countryFlag.AR,
    },
    AS: {
      code: "AS",
      name: "American Samoa",
      currency: "USD",
      flag: countryFlag.AS,
    },
    AT: { code: "AT", name: "Austria", currency: "EUR", flag: countryFlag.AT },
    AU: {
      code: "AU",
      name: "Australia",
      currency: "AUD",
      flag: countryFlag.AU,
    },
    AW: { code: "AW", name: "Aruba", currency: "AWG", flag: countryFlag.AW },
    AX: {
      code: "AX",
      name: "Åland Islands",
      currency: "EUR",
      flag: countryFlag.AX,
    },
    AZ: {
      code: "AZ",
      name: "Azerbaijan",
      currency: "AZN",
      flag: countryFlag.AZ,
    },
    BA: {
      code: "BA",
      name: "Bosnia and Herzegovina",
      currency: "BAM",
      flag: countryFlag.BA,
    },
    BB: { code: "BB", name: "Barbados", currency: "BBD", flag: countryFlag.BB },
    BD: {
      code: "BD",
      name: "Bangladesh",
      currency: "BDT",
      flag: countryFlag.BD,
    },
    BE: { code: "BE", name: "Belgium", currency: "EUR", flag: countryFlag.BE },
    BF: {
      code: "BF",
      name: "Burkina Faso",
      currency: "XOF",
      flag: countryFlag.BF,
    },
    BG: { code: "BG", name: "Bulgaria", currency: "BGN", flag: countryFlag.BG },
    BH: { code: "BH", name: "Bahrain", currency: "BHD", flag: countryFlag.BH },
    BI: { code: "BI", name: "Burundi", currency: "BIF", flag: countryFlag.BI },
    BJ: { code: "BJ", name: "Benin", currency: "XOF", flag: countryFlag.BJ },
    BL: {
      code: "BL",
      name: "Saint Barthélemy",
      currency: "EUR",
      flag: countryFlag.BL,
    },
    BM: { code: "BM", name: "Bermuda", currency: "BMD", flag: countryFlag.BM },
    BN: {
      code: "BN",
      name: "Brunei Darussalam",
      currency: "BND",
      flag: countryFlag.BN,
    },
    BO: {
      code: "BO",
      name: "Bolivia (Plurinational State of)",
      currency: "BOB",
      flag: countryFlag.BO,
    },
    BQ: {
      code: "BQ",
      name: "Bonaire, Sint Eustatius and Saba",
      currency: "USD",
      flag: countryFlag.BQ,
    },
    BR: { code: "BR", name: "Brazil", currency: "BRL", flag: countryFlag.BR },
    BS: { code: "BS", name: "Bahamas", currency: "BSD", flag: countryFlag.BS },
    BT: { code: "BT", name: "Bhutan", currency: "BTN", flag: countryFlag.BT },
    BV: {
      code: "BV",
      name: "Bouvet Island",
      currency: "NOK",
      flag: countryFlag.BV,
    },
    BW: { code: "BW", name: "Botswana", currency: "BWP", flag: countryFlag.BW },
    BY: { code: "BY", name: "Belarus", currency: "BYN", flag: countryFlag.BY },
    BZ: { code: "BZ", name: "Belize", currency: "BZD", flag: countryFlag.BZ },
    CA: { code: "CA", name: "Canada", currency: "CAD", flag: countryFlag.CA },
    CC: {
      code: "CC",
      name: "Cocos (Keeling) Islands",
      currency: "AUD",
      flag: countryFlag.CC,
    },
    CD: {
      code: "CD",
      name: "Congo, Democratic Republic of the",
      currency: "CDF",
      flag: countryFlag.CD,
    },
    CF: {
      code: "CF",
      name: "Central African Republic",
      currency: "XAF",
      flag: countryFlag.CF,
    },
    CG: { code: "CG", name: "Congo", currency: "XAF", flag: countryFlag.CG },
    CH: {
      code: "CH",
      name: "Switzerland",
      currency: "CHF",
      flag: countryFlag.CH,
    },
    CI: {
      code: "CI",
      name: "Côte d'Ivoire",
      currency: "XOF",
      flag: countryFlag.CI,
    },
    CK: {
      code: "CK",
      name: "Cook Islands",
      currency: "NZD",
      flag: countryFlag.CK,
    },
    CL: { code: "CL", name: "Chile", currency: "CLP", flag: countryFlag.CL },
    CM: { code: "CM", name: "Cameroon", currency: "XAF", flag: countryFlag.CM },
    CN: { code: "CN", name: "China", currency: "CNY", flag: countryFlag.CN },
    CO: { code: "CO", name: "Colombia", currency: "COP", flag: countryFlag.CO },
    CR: {
      code: "CR",
      name: "Costa Rica",
      currency: "CRC",
      flag: countryFlag.CR,
    },
    CU: { code: "CU", name: "Cuba", currency: "CUP", flag: countryFlag.CU },
    CV: {
      code: "CV",
      name: "Cabo Verde",
      currency: "CVE",
      flag: countryFlag.CV,
    },
    CW: { code: "CW", name: "Curaçao", currency: "ANG", flag: countryFlag.CW },
    CX: {
      code: "CX",
      name: "Christmas Island",
      currency: "AUD",
      flag: countryFlag.CX,
    },
    CY: { code: "CY", name: "Cyprus", currency: "EUR", flag: countryFlag.CY },
    CZ: { code: "CZ", name: "Czechia", currency: "CZK", flag: countryFlag.CZ },
    DE: { code: "DE", name: "Germany", currency: "EUR", flag: countryFlag.DE },
    DJ: { code: "DJ", name: "Djibouti", currency: "DJF", flag: countryFlag.DJ },
    DK: { code: "DK", name: "Denmark", currency: "DKK", flag: countryFlag.DK },
    DM: { code: "DM", name: "Dominica", currency: "XCD", flag: countryFlag.DM },
    DO: {
      code: "DO",
      name: "Dominican Republic",
      currency: "DOP",
      flag: countryFlag.DO,
    },
    DZ: { code: "DZ", name: "Algeria", currency: "DZD", flag: countryFlag.DZ },
    EC: { code: "EC", name: "Ecuador", currency: "USD", flag: countryFlag.EC },
    EE: { code: "EE", name: "Estonia", currency: "EUR", flag: countryFlag.EE },
    EG: { code: "EG", name: "Egypt", currency: "EGP", flag: countryFlag.EG },
    EH: {
      code: "EH",
      name: "Western Sahara",
      currency: "MAD",
      flag: countryFlag.EH,
    },
    ER: { code: "ER", name: "Eritrea", currency: "ERN", flag: countryFlag.ER },
    ES: { code: "ES", name: "Spain", currency: "EUR", flag: countryFlag.ES },
    ET: { code: "ET", name: "Ethiopia", currency: "ETB", flag: countryFlag.ET },
    FI: { code: "FI", name: "Finland", currency: "EUR", flag: countryFlag.FI },
    FJ: { code: "FJ", name: "Fiji", currency: "FJD", flag: countryFlag.FJ },
    FK: {
      code: "FK",
      name: "Falkland Islands (Malvinas)",
      currency: "FKP",
      flag: countryFlag.FK,
    },
    FM: {
      code: "FM",
      name: "Micronesia (Federated States of)",
      currency: "USD",
      flag: countryFlag.FM,
    },
    FO: {
      code: "FO",
      name: "Faroe Islands",
      currency: "DKK",
      flag: countryFlag.FO,
    },
    FR: { code: "FR", name: "France", currency: "EUR", flag: countryFlag.FR },
    GA: { code: "GA", name: "Gabon", currency: "XAF", flag: countryFlag.GA },
    GB: {
      code: "GB",
      name: "United Kingdom of Great Britain and Northern Ireland",
      currency: "GBP",
      flag: countryFlag.GB,
    },
    GD: { code: "GD", name: "Grenada", currency: "XCD", flag: countryFlag.GD },
    GE: { code: "GE", name: "Georgia", currency: "GEL", flag: countryFlag.GE },
    GF: {
      code: "GF",
      name: "French Guiana",
      currency: "EUR",
      flag: countryFlag.GF,
    },
    GG: { code: "GG", name: "Guernsey", currency: "GBP", flag: countryFlag.GG },
    GH: { code: "GH", name: "Ghana", currency: "GHS", flag: countryFlag.GH },
    GI: {
      code: "GI",
      name: "Gibraltar",
      currency: "GIP",
      flag: countryFlag.GI,
    },
    GL: {
      code: "GL",
      name: "Greenland",
      currency: "DKK",
      flag: countryFlag.GL,
    },
    GM: { code: "GM", name: "Gambia", currency: "GMD", flag: countryFlag.GM },
    GN: { code: "GN", name: "Guinea", currency: "GNF", flag: countryFlag.GN },
    GR: { code: "GR", name: "Greece", currency: "EUR", flag: countryFlag.GR },
    GS: {
      code: "GS",
      name: "South Georgia and the South Sandwich Islands",
      currency: "GBP",
      flag: countryFlag.GS,
    },
    GT: {
      code: "GT",
      name: "Guatemala",
      currency: "GTQ",
      flag: countryFlag.GT,
    },
    GU: { code: "GU", name: "Guam", currency: "USD", flag: countryFlag.GU },
    GW: {
      code: "GW",
      name: "Guinea-Bissau",
      currency: "XOF",
      flag: countryFlag.GW,
    },
    GY: { code: "GY", name: "Guyana", currency: "GYD", flag: countryFlag.GY },
    HK: {
      code: "HK",
      name: "Hong Kong",
      currency: "HKD",
      flag: countryFlag.HK,
    },
    HM: {
      code: "HM",
      name: "Heard Island and McDonald Islands",
      currency: "AUD",
      flag: countryFlag.HM,
    },
    HN: { code: "HN", name: "Honduras", currency: "HNL", flag: countryFlag.HN },
    HR: { code: "HR", name: "Croatia", currency: "EUR", flag: countryFlag.HR },
    HT: { code: "HT", name: "Haiti", currency: "HTG", flag: countryFlag.HT },
    HU: { code: "HU", name: "Hungary", currency: "HUF", flag: countryFlag.HU },
    ID: {
      code: "ID",
      name: "Indonesia",
      currency: "IDR",
      flag: countryFlag.ID,
    },
    IE: { code: "IE", name: "Ireland", currency: "EUR", flag: countryFlag.IE },
    IL: { code: "IL", name: "Israel", currency: "ILS", flag: countryFlag.IL },
    IM: {
      code: "IM",
      name: "Isle of Man",
      currency: "GBP",
      flag: countryFlag.IM,
    },
    IN: { code: "IN", name: "India", currency: "INR", flag: countryFlag.IN },
    IO: {
      code: "IO",
      name: "British Indian Ocean Territory",
      currency: "USD",
      flag: countryFlag.IO,
    },
    IQ: { code: "IQ", name: "Iraq", currency: "IQD", flag: countryFlag.IQ },
    IR: {
      code: "IR",
      name: "Iran (Islamic Republic of)",
      currency: "IRR",
      flag: countryFlag.IR,
    },
    IS: { code: "IS", name: "Iceland", currency: "ISK", flag: countryFlag.IS },
    IT: { code: "IT", name: "Italy", currency: "EUR", flag: countryFlag.IT },
    JE: { code: "JE", name: "Jersey", currency: "GBP", flag: countryFlag.JE },
    JM: { code: "JM", name: "Jamaica", currency: "JMD", flag: countryFlag.JM },
    JO: { code: "JO", name: "Jordan", currency: "JOD", flag: countryFlag.JO },
    JP: { code: "JP", name: "Japan", currency: "JPY", flag: countryFlag.JP },
    KE: { code: "KE", name: "Kenya", currency: "KES", flag: countryFlag.KE },
    KG: {
      code: "KG",
      name: "Kyrgyzstan",
      currency: "KGS",
      flag: countryFlag.KG,
    },
    KH: { code: "KH", name: "Cambodia", currency: "KHR", flag: countryFlag.KH },
    KI: { code: "KI", name: "Kiribati", currency: "AUD", flag: countryFlag.KI },
    KM: { code: "KM", name: "Comoros", currency: "KMF", flag: countryFlag.KM },
    KN: {
      code: "KN",
      name: "Saint Kitts and Nevis",
      currency: "XCD",
      flag: countryFlag.KN,
    },
    KP: {
      code: "KP",
      name: "Korea (Democratic People's Republic of)",
      currency: "KPW",
      flag: countryFlag.KP,
    },
    KR: {
      code: "KR",
      name: "Korea, Republic of",
      currency: "KRW",
      flag: countryFlag.KR,
    },
    KW: { code: "KW", name: "Kuwait", currency: "KWD", flag: countryFlag.KW },
    KY: {
      code: "KY",
      name: "Cayman Islands",
      currency: "KYD",
      flag: countryFlag.KY,
    },
    KZ: {
      code: "KZ",
      name: "Kazakhstan",
      currency: "KZT",
      flag: countryFlag.KZ,
    },
    LA: {
      code: "LA",
      name: "Lao People's Democratic Republic",
      currency: "LAK",
      flag: countryFlag.LA,
    },
    LB: { code: "LB", name: "Lebanon", currency: "LBP", flag: countryFlag.LB },
    LC: {
      code: "LC",
      name: "Saint Lucia",
      currency: "XCD",
      flag: countryFlag.LC,
    },
    LI: {
      code: "LI",
      name: "Liechtenstein",
      currency: "CHF",
      flag: countryFlag.LI,
    },
    LK: {
      code: "LK",
      name: "Sri Lanka",
      currency: "LKR",
      flag: countryFlag.LK,
    },
    LR: { code: "LR", name: "Liberia", currency: "LRD", flag: countryFlag.LR },
    LS: { code: "LS", name: "Lesotho", currency: "LSL", flag: countryFlag.LS },
    LT: {
      code: "LT",
      name: "Lithuania",
      currency: "EUR",
      flag: countryFlag.LT,
    },
    LU: {
      code: "LU",
      name: "Luxembourg",
      currency: "EUR",
      flag: countryFlag.LU,
    },
    LV: { code: "LV", name: "Latvia", currency: "EUR", flag: countryFlag.LV },
    LY: { code: "LY", name: "Libya", currency: "LYD", flag: countryFlag.LY },
    MA: { code: "MA", name: "Morocco", currency: "MAD", flag: countryFlag.MA },
    MC: { code: "MC", name: "Monaco", currency: "EUR", flag: countryFlag.MC },
    MD: {
      code: "MD",
      name: "Moldova, Republic of",
      currency: "MDL",
      flag: countryFlag.MD,
    },
    ME: {
      code: "ME",
      name: "Montenegro",
      currency: "EUR",
      flag: countryFlag.ME,
    },
    MF: {
      code: "MF",
      name: "Saint Martin (French part)",
      currency: "EUR",
      flag: countryFlag.MF,
    },
    MG: {
      code: "MG",
      name: "Madagascar",
      currency: "MGA",
      flag: countryFlag.MG,
    },
    MH: {
      code: "MH",
      name: "Marshall Islands",
      currency: "USD",
      flag: countryFlag.MH,
    },
    MK: {
      code: "MK",
      name: "North Macedonia",
      currency: "MKD",
      flag: countryFlag.MK,
    },
    ML: { code: "ML", name: "Mali", currency: "XOF", flag: countryFlag.ML },
    MM: { code: "MM", name: "Myanmar", currency: "MMK", flag: countryFlag.MM },
    MN: { code: "MN", name: "Mongolia", currency: "MNT", flag: countryFlag.MN },
    MO: { code: "MO", name: "Macao", currency: "MOP", flag: countryFlag.MO },
    MP: {
      code: "MP",
      name: "Northern Mariana Islands",
      currency: "USD",
      flag: countryFlag.MP,
    },
    MQ: {
      code: "MQ",
      name: "Martinique",
      currency: "EUR",
      flag: countryFlag.MQ,
    },
    MR: {
      code: "MR",
      name: "Mauritania",
      currency: "MRU",
      flag: countryFlag.MR,
    },
    MS: {
      code: "MS",
      name: "Montserrat",
      currency: "XCD",
      flag: countryFlag.MS,
    },
    MT: { code: "MT", name: "Malta", currency: "EUR", flag: countryFlag.MT },
    MU: {
      code: "MU",
      name: "Mauritius",
      currency: "MUR",
      flag: countryFlag.MU,
    },
    MV: { code: "MV", name: "Maldives", currency: "MVR", flag: countryFlag.MV },
    MW: { code: "MW", name: "Malawi", currency: "MWK", flag: countryFlag.MW },
    MX: { code: "MX", name: "Mexico", currency: "MXN", flag: countryFlag.MX },
    MY: { code: "MY", name: "Malaysia", currency: "MYR", flag: countryFlag.MY },
    MZ: {
      code: "MZ",
      name: "Mozambique",
      currency: "MZN",
      flag: countryFlag.MZ,
    },
    NA: { code: "NA", name: "Namibia", currency: "NAD", flag: countryFlag.NA },
    NC: {
      code: "NC",
      name: "New Caledonia",
      currency: "XPF",
      flag: countryFlag.NC,
    },
    NE: { code: "NE", name: "Niger", currency: "XOF", flag: countryFlag.NE },
    NF: {
      code: "NF",
      name: "Norfolk Island",
      currency: "AUD",
      flag: countryFlag.NF,
    },
    NG: { code: "NG", name: "Nigeria", currency: "NGN", flag: countryFlag.NG },
    NI: {
      code: "NI",
      name: "Nicaragua",
      currency: "NIO",
      flag: countryFlag.NI,
    },
    NL: {
      code: "NL",
      name: "Netherlands",
      currency: "EUR",
      flag: countryFlag.NL,
    },
    NO: { code: "NO", name: "Norway", currency: "NOK", flag: countryFlag.NO },
    NP: { code: "NP", name: "Nepal", currency: "NPR", flag: countryFlag.NP },
    NR: { code: "NR", name: "Nauru", currency: "AUD", flag: countryFlag.NR },
    NU: { code: "NU", name: "Niue", currency: "NZD", flag: countryFlag.NU },
    NZ: {
      code: "NZ",
      name: "New Zealand",
      currency: "NZD",
      flag: countryFlag.NZ,
    },
    OM: { code: "OM", name: "Oman", currency: "OMR", flag: countryFlag.OM },
    PA: { code: "PA", name: "Panama", currency: "PAB", flag: countryFlag.PA },
    PE: { code: "PE", name: "Peru", currency: "PEN", flag: countryFlag.PE },
    PF: {
      code: "PF",
      name: "French Polynesia",
      currency: "XPF",
      flag: countryFlag.PF,
    },
    PG: {
      code: "PG",
      name: "Papua New Guinea",
      currency: "PGK",
      flag: countryFlag.PG,
    },
    PH: {
      code: "PH",
      name: "Philippines",
      currency: "PHP",
      flag: countryFlag.PH,
    },
    PK: { code: "PK", name: "Pakistan", currency: "PKR", flag: countryFlag.PK },
    PL: { code: "PL", name: "Poland", currency: "PLN", flag: countryFlag.PL },
    PM: {
      code: "PM",
      name: "Saint Pierre and Miquelon",
      currency: "EUR",
      flag: countryFlag.PM,
    },
    PN: { code: "PN", name: "Pitcairn", currency: "NZD", flag: countryFlag.PN },
    PR: {
      code: "PR",
      name: "Puerto Rico",
      currency: "USD",
      flag: countryFlag.PR,
    },
    PS: {
      code: "PS",
      name: "Palestine, State of",
      currency: "ILS",
      flag: countryFlag.PS,
    },
    PT: { code: "PT", name: "Portugal", currency: "EUR", flag: countryFlag.PT },
    PW: { code: "PW", name: "Palau", currency: "USD", flag: countryFlag.PW },
    PY: { code: "PY", name: "Paraguay", currency: "PYG", flag: countryFlag.PY },
    QA: { code: "QA", name: "Qatar", currency: "QAR", flag: countryFlag.QA },
    RE: { code: "RE", name: "Réunion", currency: "EUR", flag: countryFlag.RE },
    RO: { code: "RO", name: "Romania", currency: "RON", flag: countryFlag.RO },
    RS: { code: "RS", name: "Serbia", currency: "RSD", flag: countryFlag.RS },
    RU: {
      code: "RU",
      name: "Russian Federation",
      currency: "RUB",
      flag: countryFlag.RU,
    },
    RW: { code: "RW", name: "Rwanda", currency: "RWF", flag: countryFlag.RW },
    SA: {
      code: "SA",
      name: "Saudi Arabia",
      currency: "SAR",
      flag: countryFlag.SA,
    },
    SB: {
      code: "SB",
      name: "Solomon Islands",
      currency: "SBD",
      flag: countryFlag.SB,
    },
    SC: {
      code: "SC",
      name: "Seychelles",
      currency: "SCR",
      flag: countryFlag.SC,
    },
    SD: { code: "SD", name: "Sudan", currency: "SDG", flag: countryFlag.SD },
    SE: { code: "SE", name: "Sweden", currency: "SEK", flag: countryFlag.SE },
    SG: {
      code: "SG",
      name: "Singapore",
      currency: "SGD",
      flag: countryFlag.SG,
    },
    SH: {
      code: "SH",
      name: "Saint Helena, Ascension and Tristan da Cunha",
      currency: "SHP",
      flag: countryFlag.SH,
    },
    SI: { code: "SI", name: "Slovenia", currency: "EUR", flag: countryFlag.SI },
    SJ: {
      code: "SJ",
      name: "Svalbard and Jan Mayen",
      currency: "NOK",
      flag: countryFlag.SJ,
    },
    SK: { code: "SK", name: "Slovakia", currency: "EUR", flag: countryFlag.SK },
    SL: {
      code: "SL",
      name: "Sierra Leone",
      currency: "SLL",
      flag: countryFlag.SL,
    },
    SM: {
      code: "SM",
      name: "San Marino",
      currency: "EUR",
      flag: countryFlag.SM,
    },
    SN: { code: "SN", name: "Senegal", currency: "XOF", flag: countryFlag.SN },
    SO: { code: "SO", name: "Somalia", currency: "SOS", flag: countryFlag.SO },
    SR: { code: "SR", name: "Suriname", currency: "SRD", flag: countryFlag.SR },
    SS: {
      code: "SS",
      name: "South Sudan",
      currency: "SSP",
      flag: countryFlag.SS,
    },
    ST: {
      code: "ST",
      name: "Sao Tome and Principe",
      currency: "STN",
      flag: countryFlag.ST,
    },
    SV: {
      code: "SV",
      name: "El Salvador",
      currency: "USD",
      flag: countryFlag.SV,
    },
    SX: {
      code: "SX",
      name: "Sint Maarten (Dutch part)",
      currency: "ANG",
      flag: countryFlag.SX,
    },
    SY: {
      code: "SY",
      name: "Syrian Arab Republic",
      currency: "SYP",
      flag: countryFlag.SY,
    },
    SZ: { code: "SZ", name: "Eswatini", currency: "SZL", flag: countryFlag.SZ },
    TC: {
      code: "TC",
      name: "Turks and Caicos Islands",
      currency: "USD",
      flag: countryFlag.TC,
    },
    TD: { code: "TD", name: "Chad", currency: "XAF", flag: countryFlag.TD },
    TF: {
      code: "TF",
      name: "French Southern Territories",
      currency: "EUR",
      flag: countryFlag.TF,
    },
    TG: { code: "TG", name: "Togo", currency: "XOF", flag: countryFlag.TG },
    TH: { code: "TH", name: "Thailand", currency: "THB", flag: countryFlag.TH },
    TJ: {
      code: "TJ",
      name: "Tajikistan",
      currency: "TJS",
      flag: countryFlag.TJ,
    },
    TK: { code: "TK", name: "Tokelau", currency: "NZD", flag: countryFlag.TK },
    TL: {
      code: "TL",
      name: "Timor-Leste",
      currency: "USD",
      flag: countryFlag.TL,
    },
    TM: {
      code: "TM",
      name: "Turkmenistan",
      currency: "TMT",
      flag: countryFlag.TM,
    },
    TN: { code: "TN", name: "Tunisia", currency: "TND", flag: countryFlag.TN },
    TO: { code: "TO", name: "Tonga", currency: "TOP", flag: countryFlag.TO },
    TR: { code: "TR", name: "Turkey", currency: "TRY", flag: countryFlag.TR },
    TT: {
      code: "TT",
      name: "Trinidad and Tobago",
      currency: "TTD",
      flag: countryFlag.TT,
    },
    TV: { code: "TV", name: "Tuvalu", currency: "AUD", flag: countryFlag.TV },
    TW: {
      code: "TW",
      name: "Taiwan, Province of China",
      currency: "TWD",
      flag: countryFlag.TW,
    },
    TZ: {
      code: "TZ",
      name: "Tanzania, United Republic of",
      currency: "TZS",
      flag: countryFlag.TZ,
    },
    UA: { code: "UA", name: "Ukraine", currency: "UAH", flag: countryFlag.UA },
    UG: { code: "UG", name: "Uganda", currency: "UGX", flag: countryFlag.UG },
    UM: {
      code: "UM",
      name: "United States Minor Outlying Islands",
      currency: "USD",
      flag: countryFlag.UM,
    },
    US: {
      code: "US",
      name: "United States of America",
      currency: "USD",
      flag: countryFlag.US,
    },
    UY: { code: "UY", name: "Uruguay", currency: "UYU", flag: countryFlag.UY },
    UZ: {
      code: "UZ",
      name: "Uzbekistan",
      currency: "UZS",
      flag: countryFlag.UZ,
    },
    VA: { code: "VA", name: "Holy See", currency: "EUR", flag: countryFlag.VA },
    VC: {
      code: "VC",
      name: "Saint Vincent and the Grenadines",
      currency: "XCD",
      flag: countryFlag.VC,
    },
    VE: {
      code: "VE",
      name: "Venezuela (Bolivarian Republic of)",
      currency: "VES",
      flag: countryFlag.VE,
    },
    VG: {
      code: "VG",
      name: "Virgin Islands (British)",
      currency: "USD",
      flag: countryFlag.VG,
    },
    VI: {
      code: "VI",
      name: "Virgin Islands (U.S.)",
      currency: "USD",
      flag: countryFlag.VI,
    },
    VN: { code: "VN", name: "Viet Nam", currency: "VND", flag: countryFlag.VN },
    VU: { code: "VU", name: "Vanuatu", currency: "VUV", flag: countryFlag.VU },
    WF: {
      code: "WF",
      name: "Wallis and Futuna",
      currency: "XPF",
      flag: countryFlag.WF,
    },
    WS: { code: "WS", name: "Samoa", currency: "WST", flag: countryFlag.WS },
    YE: { code: "YE", name: "Yemen", currency: "YER", flag: countryFlag.YE },
    YT: { code: "YT", name: "Mayotte", currency: "EUR", flag: countryFlag.YT },
    ZA: {
      code: "ZA",
      name: "South Africa",
      currency: "ZAR",
      flag: countryFlag.ZA,
    },
    ZM: { code: "ZM", name: "Zambia", currency: "ZMW", flag: countryFlag.ZM },
    ZW: { code: "ZW", name: "Zimbabwe", currency: "ZWL", flag: countryFlag.ZW },
  },
};
