export const weatherIndicators = {
  ua: {
    temp: "Температура",
    pressure: "Тиск",
    humidity: "Вологість",
    clouds: "Хмарність",
    rain: "Атмосферні опади",
    snow: "Снігопад",
    unit_1: "°C",
    unit_2: "гПа",
    unit_3: "%",
    unit_4: "мм/ч",
  },
  ru: {
    temp: "Температура",
    pressure: "Давление",
    humidity: "Влажность",
    clouds: "Облачность",
    rain: "Атмосферные осадки",
    snow: "Снегопад",
    unit_1: "°C",
    unit_2: "гПа",
    unit_3: "%",
    unit_4: "мм/ч",
  },
  en: {
    temp: "Temperature",
    pressure: "Pressure",
    humidity: "Humidity",
    clouds: "Cloud cover",
    rain: "Precipitation",
    snow: "Snowfall",
    unit_1: "°C",
    unit_2: "hPa",
    unit_3: "%",
    unit_4: "mm/h",
  },
};
